import { Character } from "../../../../noname/library/element/index.js";
import { _status, get, lib } from "../../../../noname.js";

const bool = _status.connectMode ? lib.configOL.jinEx : get.config("jinEx");

export default {
	// 分组1：野心家
	gz_zhonghui: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakequanji", "fakepaiyi"],
		hasSkinInGuozhan: true,
	}),
	gz_simazhao: new Character({
		sex: "male",
		group: "ye",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhaoxin", "gzsuzhi"],
		hasSkinInGuozhan: true,
	}),
	gz_gongsunyuan: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakehuaiyi", "fakezisui"],
		hasSkinInGuozhan: true,
	}),
	gz_sunchen: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakeshilu", "fakexiongnve"],
		dieAudios: ["pe_sunchen"],
		hasSkinInGuozhan: false,
	}),
	// 分组2：谷爱凌
	gz_tangzi: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzxingzhao"],
		doubleGroup: ["wei", "wu"],
		hasSkinInGuozhan: true,
	}),
	gz_mengda: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["qiuan", "liangfan"],
		dieAudios: ["pe_mengda"],
		doubleGroup: ["wei", "shu"],
		hasSkinInGuozhan: false,
	}),
	gz_liuqi: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzwenji", "gztunjiang"],
		doubleGroup: ["qun", "shu"],
		hasSkinInGuozhan: true,
	}),
	gz_mifangfushiren: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["mffengshi"],
		doubleGroup: ["wu", "shu"],
		hasSkinInGuozhan: false,
	}),
	gz_shixie: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzbiluan", "gzrelixia"],
		doubleGroup: ["wu", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_zhanglu: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzrebushi", "gzremidao"],
		doubleGroup: ["wei", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_db_wenyang: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_quedi", "gz_zhuifeng", "gz_chongjian"],
		doubleGroup: ["wei", "wu"],
	}),
	gz_dongzhao: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["quanjin", "zaoyun"],
		// doubleGroup: ["wei", "qun"],
		hasSkinInGuozhan: false,
	}),
	gz_re_xushu: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhuhai", "gzpozhen", "gzjiancai"],
		hasSkinInGuozhan: true,
	}),
	// 那男舅
	gz_wujing: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["donggui", "fengyang"],
		hasSkinInGuozhan: true,
	}),
	// 严虎
	gz_yanbaihu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhidao", "gzyjili"],
		hasSkinInGuozhan: true,
	}),
	gz_xuyou: new Character({
		doubleGroup: ["wei", "qun"],
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzchenglve", "gzshicai"],
		hasSkinInGuozhan: true,
	}),
	gz_xiahouba: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzbaolie"],
		doubleGroup: ["wei", "shu"],
		hasSkinInGuozhan: true,
	}),
	gz_panjun: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzcongcha", "xinfu_gongqing"],
		doubleGroup: ["shu", "wu"],
		hasSkinInGuozhan: true,
	}),
	gz_huangzu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzxishe"],
		hasSkinInGuozhan: true,
	}),
	gz_zhugeke: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["aocai", "gzduwu"],
		hasSkinInGuozhan: true,
	}),
	gz_wenqin: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzjinfa"],
		dieAudios: ["pe_wenqin"],
		doubleGroup: ["wei", "wu"],
		hasSkinInGuozhan: true,
	}),
	gz_xf_sufei: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzlianpian"],
		doubleGroup: ["wu", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_liuba: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gztongduo", "qingyin"],
		hasSkinInGuozhan: true,
	}),
	gz_pengyang: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gztongling", "gzjinyu"],
		doubleGroup: ["shu", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_zhuling: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzjuejue", "gzfangyuan"],
		hasSkinInGuozhan: true,
	}),
	gz_wangyi: new Character({
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhenlie", "miji"],
	}),
	gz_wangji: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzqizhi", "gzjinqu"],
	}),
	gz_xurong: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzxionghuo"],
	}),
	gz_xianglang: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzkanji", "dcqianzheng"],
	}),
	gz_tengyin: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzchenjian", "gzxixiu"],
	}),
	gz_re_panshu: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zhiren", "gzyaner"],
	}),
	gz_maliang: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xiemu", "naman"],
		dieAudios: ["old_maliang"],
	}),
	gz_caozhen: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzsidi"],
	}),
	gz_bulianshi: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["old_anxu", "zhuiyi"],
	}),
	gz_mazhong: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["twfuman"],
	}),
	gz_ol_lisu: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qiaoyan", "xianzhu"],
	}),

	gz_jun_liubei: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["zhangwu", "jizhao", "shouyue"],
	}),
	gz_jun_zhangjiao: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["wuxin", "hongfa", "wendao"],
	}),
	gz_jun_sunquan: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["jiahe", "lianzi", "jubao"],
	}),

	gz_lingcao: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzdujin"],
	}),
	gz_lifeng: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["tunchu", "shuliang"],
	}),
	gz_beimihu: new Character({
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzguishu", "gzyuanyu"],
	}),
	gz_jianggan: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["weicheng", "daoshu"],
	}),
	gz_mb_luxun: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_mb_qianxun", "gz_mb_duoshi"],
		img: "image/character/sb_luxun.jpg",
		dieAudios: ["sb_luxun"],
	}),
	gz_huaxin: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["wanggui", "fakexibing"],
	}),
	gz_luyusheng: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakezhente", "fakezhiwei"],
	}),
	gz_zongyu: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["zyqiao", "gzchengshang"],
	}),
	gz_miheng: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakekuangcai", "gzshejian"],
		hasSkinInGuozhan: true,
		dieAudios: ["re_miheng"],
	}),
	gz_fengxi: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzyusui", "gzboyan"],
		hasSkinInGuozhan: true,
	}),
	gz_dengzhi: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzjianliang", "gzweimeng"],
		hasSkinInGuozhan: true,
	}),
	gz_re_nanhualaoxian: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzgongxiu", "gztaidan", "gzjinghe_new"],
	}),
	gz_zhouyi: new Character({
		sex: "female",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhukou", "gzduannian", "gzlianyou"],
	}),
	gz_re_xunchen: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzfenglve", "gzanyong"],
	}),
	gz_lvlingqi: new Character({
		sex: "female",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["guowu", "gzshenwei", "gzzhuangrong"],
		hasSkinInGuozhan: true,
	}),
	gz_dc_yanghu: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzdeshao", "gzmingfa"],
	}),

	gz_jun_caocao: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["jianan", "huibian", "gzzongyu"],
	}),

	gz_liaohua: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzdangxian"],
	}),
	gz_zhugejin: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzhuanshi", "gzhongyuan", "gzmingzhe"],
	}),
	gz_yangxiu: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzdanlao", "gzjilei"],
	}),
	gz_zumao: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["yinbing", "juedi"],
	}),
	gz_fuwan: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzmoukui"],
		img: "image/character/tw_fuwan.jpg",
	}),
	gz_chendao: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["drlt_wanglie"],
	}),
	gz_tw_tianyu: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhenxi", "gzjiansu"],
	}),
	gz_tw_liufuren: new Character({
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhuidu", "gzshigong"],
	}),
	gz_old_huaxiong: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzyaowu", "gzshiyong"],
	}),
	gz_tw_xiahoushang: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gztanfeng"],
	}),

	gz_xf_huangquan: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzdianhu", "gzjianji"],
		doubleGroup: ["wei", "shu"],
	}),
	gz_guohuai: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzduanshi", "gzjingce"],
		hasSkinInGuozhan: true,
	}),
	gz_guanqiujian: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzzhengrong", "gzhongju"],
	}),
	gz_zhujun: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gzgongjian", "gzkuimang"],
	}),
	gz_chengong: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzyinpan", "gzxingmou"],
		doubleGroup: ["wei", "qun"],
		hasSkinInGuozhan: true,
	}),
	gz_re_xugong: new Character({
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzbiaozhao", "gzyechou"],
		doubleGroup: ["wu", "qun"],
	}),
	// 神谷爱凌
	gz_key_ushio: new Character({
		sex: "female",
		group: "key",
		hp: 3,
		maxHp: 3,
		//hujia: 999,
		skills: ["ushio_huanxin", "ushio_xilv"],
		// 就你势力多
		doubleGroup: ["key", "wei", "shu", "wu", "qun", "jin"],
	}),

	gz_wangling: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakemibei"],
	}),
	gz_yanyan: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakejuzhan"],
	}),
	gz_xin_zhuran: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakedanshou"],
	}),
	gz_gaoshun: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakexunxi", "fakehuanjia"],
		hasSkinInGuozhan: true,
	}),
	//OL限时武将
	gz_re_xusheng: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["repojun"],
	}),
	// 怎么还冒出来一个体力上限不一样的呢？
	gz_ol_sb_sunjian: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 5,
		hujia: 0,
		skills: ["olsbhulie", "olsbyipo"],
	}),
	gz_liuyan: new Character({
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xinfu_tushe", "xinfu_limu"],
	}),
	gz_re_huanggai: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["rekurou", "zhaxiang"],
	}),
	gz_re_xuzhu: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["new_reluoyi"],
	}),
	gz_ol_weiyan: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["xinkuanggu", "reqimou"],
		tempname: ["ol_weiyan"],
	}),
	gz_ol_yanwen: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["olshuangxiong"],
		names: "颜|良-文|丑",
	}),
	gz_caochong: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["chengxiang", "renxin"],
	}),
	gz_zhangsong: {
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["qiangzhi", "xiantu"],
	},
	gz_re_huangyueying: {
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["rejizhi", "reqicai"],
	},
	gz_re_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["new_rejianxiong"],
		junName: "gz_jun_caocao",
	},
	gz_re_zhangjiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["xinleiji", "xinguidao"],
		junName: "gz_jun_zhangjiao",
	},
	gz_re_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["reqianxun", "relianying"],
		clans: ["吴郡陆氏"],
	},
	gz_ol_zhonghui: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_ol_quanji", "gz_ol_paiyi", "gz_yaopan"],
		dieAudios: ["zhonghui"],
	}),
	gz_ol_wuyi: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_ol_benxi", "gz_ol_zhuanzheng"],
		dieAudios: ["wuyi"],
	}),
};

export const sort = "";
